-- Seed data for products table
INSERT INTO products (name, description, price, category, brand, sku, stock) VALUES
('iPhone 15 Pro', 'Latest iPhone with titanium design and advanced camera system', 999.99, 'Electronics', 'Apple', 'APL-IP15P-128', 50),
('Samsung Galaxy S24', 'Premium Android smartphone with AI features', 899.99, 'Electronics', 'Samsung', 'SAM-GS24-256', 75),
('MacBook Air M3', 'Ultra-thin laptop with M3 chip and all-day battery', 1299.99, 'Electronics', 'Apple', 'APL-MBA-M3-256', 30),
('Dell XPS 13', 'Premium ultrabook with InfinityEdge display', 1099.99, 'Electronics', 'Dell', 'DEL-XPS13-512', 25),
('Sony WH-1000XM5', 'Industry-leading noise canceling wireless headphones', 399.99, 'Electronics', 'Sony', 'SNY-WH1000XM5', 100),
('AirPods Pro 2', 'Active noise cancellation with transparency mode', 249.99, 'Electronics', 'Apple', 'APL-APP2-USB', 150),
('Nike Air Max 270', 'Lifestyle shoes with Max Air cushioning', 149.99, 'Fashion', 'Nike', 'NIK-AM270-BLK-9', 200),
('Adidas Ultraboost 22', 'High-performance running shoes with Boost midsole', 179.99, 'Fashion', 'Adidas', 'ADI-UB22-WHT-10', 180),
('Levi''s 501 Original Jeans', 'Classic straight-leg jeans with authentic fit', 69.99, 'Fashion', 'Levis', 'LEV-501-BLUE-32', 300),
('The North Face Jacket', 'Waterproof and breathable outdoor jacket', 199.99, 'Fashion', 'The North Face', 'TNF-JACKET-BLK-L', 80),
('Instant Pot Duo 7-in-1', 'Multi-use programmable pressure cooker', 79.99, 'Home & Kitchen', 'Instant Pot', 'IP-DUO7-6QT', 120),
('Ninja Foodi Blender', 'Professional blender with Auto-iQ technology', 159.99, 'Home & Kitchen', 'Ninja', 'NIN-FOODI-BL', 90),
('KitchenAid Stand Mixer', 'Iconic stand mixer for all your baking needs', 379.99, 'Home & Kitchen', 'KitchenAid', 'KA-MIXER-RED', 45),
('Dyson V15 Detect', 'Cordless vacuum with laser dust detection', 649.99, 'Home & Kitchen', 'Dyson', 'DYS-V15-DETECT', 35),
('Keurig K-Elite Coffee Maker', 'Single serve K-Cup pod coffee maker', 169.99, 'Home & Kitchen', 'Keurig', 'KEU-KELITE-BLK', 70),
('PlayStation 5', 'Next-gen gaming console with ultra-fast SSD', 499.99, 'Gaming', 'Sony', 'SNY-PS5-STD', 20),
('Xbox Series X', 'Most powerful Xbox ever with 4K gaming', 499.99, 'Gaming', 'Microsoft', 'MSF-XBSX-1TB', 25),
('Nintendo Switch OLED', 'Handheld gaming system with vibrant OLED screen', 349.99, 'Gaming', 'Nintendo', 'NIN-NSW-OLED', 60),
('Steam Deck', 'Handheld PC gaming device by Valve', 399.99, 'Gaming', 'Valve', 'VAL-SDECK-64GB', 40),
('Logitech G Pro X Superlight', 'Ultra-lightweight wireless gaming mouse', 149.99, 'Gaming', 'Logitech', 'LOG-GPRO-WHITE', 85),
('Vitamix A3500', 'High-performance blender with wireless connectivity', 549.99, 'Home & Kitchen', 'Vitamix', 'VTX-A3500-BLK', 30),
('Weber Genesis II E-310', 'Premium gas grill with three burners', 799.99, 'Home & Kitchen', 'Weber', 'WEB-GEN2-E310', 15),
('Fitbit Versa 4', 'Health and fitness smartwatch with GPS', 199.99, 'Electronics', 'Fitbit', 'FIT-VERSA4-BLK', 110),
('Apple Watch Series 9', 'Advanced smartwatch with health monitoring', 399.99, 'Electronics', 'Apple', 'APL-AW9-45MM', 95),
('Canon EOS R6 Mark II', 'Full-frame mirrorless camera for professionals', 2499.99, 'Electronics', 'Canon', 'CAN-R6M2-BODY', 12),
('GoPro Hero 12', 'Action camera with 5.3K video recording', 399.99, 'Electronics', 'GoPro', 'GP-HERO12-BLK', 55),
('Bose QuietComfort 45', 'Wireless noise cancelling headphones', 329.99, 'Electronics', 'Bose', 'BSE-QC45-BLK', 75),
('JBL Charge 5', 'Portable Bluetooth speaker with powerbank', 179.99, 'Electronics', 'JBL', 'JBL-CHARGE5-BLU', 120),
('Tesla Model Y Performance Wheels', 'High-performance 21" wheels for Tesla Model Y', 2499.99, 'Automotive', 'Tesla', 'TSL-MY-PERF-WHE', 8),
('Michelin Pilot Sport 4S Tires', 'Ultra-high performance summer tires', 299.99, 'Automotive', 'Michelin', 'MCH-PS4S-245-35', 40)
ON CONFLICT (sku) DO NOTHING;
